In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np
import time

In [11]:
a=list(range(1000000))
b=list(range(1000000))

start =time.time()
result=[x+y for x,y in zip(a,b)]
end=time.time()
print("python time list:",end-start)

python time list: 0.19727516174316406


In [12]:
a_np=np.arange(10000000)
b_np=np.arange(10000000)
start=time.time()
result_np=a_np+b_np
end=time.time()
print("Numpy array Time:", end -start)

Numpy array Time: 0.07286238670349121


In [13]:
a=np.array([1,2,3,4,5,6])
print("1D Array:",a)
a.shape

1D Array: [1 2 3 4 5 6]


(6,)

In [14]:
a=np.array([[1,2],
           [3,4]])
print("2d array:",a)
a.shape

2d array: [[1 2]
 [3 4]]


(2, 2)

In [26]:
b=np.array([[[1,2,3],[3,7,8]],
           [[3,4,5],[4,7,8]],
            [[6,7,8],[4,7,9]]])
print("3d array:",b)
b.shape

3d array: [[[1 2 3]
  [3 7 8]]

 [[3 4 5]
  [4 7 8]]

 [[6 7 8]
  [4 7 9]]]


(3, 2, 3)

In [25]:
b.ndim

3

(n,) = 1D array with n elements

(1, n) = 2D array with 1 row and n columns

(n, 1) = 2D array with n rows and 1 column

(n,) ≠ (n, 1) ≠ (1, n) even though they all have n total elements


#### Slicing and Reshaping Arrays

* Slicing helps extract parts of arrays.
* Reshaping changes the shape without changing data

In [12]:
import numpy as np

arr = np.arange(12)
print("Original:", arr)

#Slicing
print("First 5:", arr[:5])
print("Last 3:", arr[-3:])
print("from 3rd to seventh:",arr[3:12:3])


Original: [ 0  1  2  3  4  5  6  7  8  9 10 11]
First 5: [0 1 2 3 4]
Last 3: [ 9 10 11]
from 3rd to seventh: [3 6 9]


In [41]:
#Reshape to 3x4
reshaped=arr.reshape(3,4)
print("Reshaped 3x4:\n",reshaped)
print("\nLast column:\n", reshaped[:,-2])
print("\nLast row:\n",reshaped[-1:])
reshaped[0][-1]=55

Reshaped 3x4:
 [[ 0  1  2 55]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Last column:
 [ 2  6 10]

Last row:
 [[ 8  9 10 11]]


##### Vectorized Operations & Broadcasting

* `Vectorized operations` allow fast element-wise operations.
* `Broadcasting` enables operations between arrays of different shapes.

# Two dimensions are compatible when:
They are equal, OR
One of them is 1.

In [42]:
x=np.array([1,2,3])
y=np.array([4,5,6])
print("Addition:", x+y)
print("Subtraction:",x-y)
print("Scalar Multiplication:",x*y)

Addition: [5 7 9]
Subtraction: [-3 -3 -3]
Scalar Multiplication: [ 4 10 18]


In [52]:
# Broadcasting example
math = np.ones((4, 5), dtype=int)
print(math)

print("-------")
vec = np.array([1, 2, 3,4,5])
print("Broadcasted Addition:\n", math + vec)
print("Broadcasted multiple:\n", math*vec)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
-------
Broadcasted Addition:
 [[2 3 4 5 6]
 [2 3 4 5 6]
 [2 3 4 5 6]
 [2 3 4 5 6]]
Broadcasted multiple:
 [[1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]]


In [ ]:
vec=

In [53]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
scalar=110
print("multiple by scalar:\n",arr*scalar)

multiple by scalar:
 [[110 220 330]
 [440 550 660]]


In [60]:
data = np.array([[80, 85, 90],
                 [70, 75, 65],
                 [88, 92, 95]])

print("Mean:", np.mean(data))
print("Sum:", np.sum(data))

student3=data[:,-2]
print(np.mean(student3))
s=np.sum(student3)
print("the sum of second column is:",s)

Mean: 82.22222222222223
Sum: 740
84.0
the sum of second column is: 252


In [61]:
data = np.array([[80, 85, 90],
                 [70, 75, 65],
                 [88, 92, 95]])

print("Mean:", np.mean(data))
print("Sum:", np.sum(data))
print("Standard Deviation:",np.std(data))
print("Max of data:",np.max(data))
print("Min of data:",np.min(data))


#Mean by axis

print("Mean per student:", np.mean(data,axis=1))
print("Mean per subject:", np.mean(data,axis=0))
student1=data[:,-3]
print(np.mean(student1))

Mean: 82.22222222222223
Sum: 740
Standard Deviation: 9.795438595792973
Max of data: 95
Min of data: 65
Mean per student: [85.         70.         91.66666667]
Mean per subject: [79.33333333 84.         83.33333333]
79.33333333333333


##### Boolean Indexing & Filtering

- Use boolean masks to filter arrays based on conditions.

- In NumPy, you can pass a boolean array inside square brackets to filter the original array. This is called boolean indexing.

In [64]:
scores = np.array([55, 72, 89, 45, 99, 66, 78])
high_scores = scores[scores > 40]
print("Scores > 70:", high_scores)
#find even scores
even_score=scores[scores%2==0]
print("even_score:", even_score)
odd_score=scores[scores%2==1]
print("odd_score:", odd_score)

Scores > 70: [55 72 89 45 99 66 78]
even_score: [72 66 78]
odd_score: [55 89 45 99]


In [65]:
#matrix mutiply

mat1 = np.array([[1, 2], [3, 4]])
mat2 = np.array([[2, 0], [1, 2]])
result=np.dot(mat1,mat2)
print("multiply:",result)

multiply: [[ 4  4]
 [10  8]]


In [67]:
mat1 = np.array([[1, 2,6], [3, 4,8] ])
mat2 = np.array([[2, 0,6], [1, 2,8] , [6,8,0]])
result=np.dot(mat1,mat2)
print("multiply:",result)

multiply: [[40 52 22]
 [58 72 50]]


In [94]:
## Activity: Matrix Calculations and Score Filtering

#Given a 5x4 matrix of student scores (rows: students, columns: subjects), find:
#- Average score per student
#- Students who scored above 75 in any subject

import numpy as np
np.random.seed(0)
student_scores=np.random.randint(50,100,size=(5,4))
print("the given data is:"
      ,student_scores)
y=np.mean(student_scores,axis=1)
print("the average score per student is :",y)
u = np.all(student_scores > 65, axis=1)#any is  used for checking all and print  if any one condition matches
students_above_76 = student_scores[u]

u = np.all(student_scores > 65, axis=1)#all is  used for checking all ans print only if all values required condition
students_above_75 = student_scores[u]
print("Students who scored above 76 any subject:\n", students_above_76)
print("Students who scored above 75 in any subject:\n", students_above_75)



the given data is: [[94 97 50 53]
 [53 89 59 69]
 [71 86 73 56]
 [74 74 62 51]
 [88 89 73 96]]
the average score per student is : [73.5  67.5  71.5  65.25 86.5 ]
Students who scored above 76 any subject:
 [[88 89 73 96]]
Students who scored above 75 in any subject:
 [[88 89 73 96]]


In [17]:
#assignment
import numpy as np
np.random.seed(5)
student_mark=np.random.randint(30,100,size=(30,))
print("the give score of 30 student is:",student_mark)
mean=np.mean(student_mark)
print("the mean score of a student is :",mean)
std=np.std(student_mark)
print("the standard deviation of the mark obthained by a student is :",std)
percentile_90 = np.percentile(student_mark, 90)
print(percentile_90)
top_10_percent_scores = student_mark[student_mark >= percentile_90]
print("Top 10% Scores:", top_10_percent_scores)
percentile_10 = np.percentile(student_mark, 10)
print(percentile_10)
bottom_10_percent_score=student_mark[student_mark <= percentile_10]
print("bottom 10% Scores:", bottom_10_percent_score)

the give score of 30 student is: [91 46 38 92 57 60 37 45 83 57 74 95 77 60 48 39 71 92 31 46 35 88 30 34
 66 81 57 61 32 98]
the mean score of a student is : 60.7
the standard deviation of the mark obthained by a student is : 21.701228843854288
92.0
Top 10% Scores: [92 95 92 98]
33.8
bottom 10% Scores: [31 30 32]


In [20]:
import numpy as np
data=np.array([91 ,46, 38, 92, 57, 60, 37, 45, 83, 57, 74, 95, 77, 60, 48, 39, 71, 92])
copy_data=np.copy(data)
print(copy_data)

[91 46 38 92 57 60 37 45 83 57 74 95 77 60 48 39 71 92]


In [24]:
view_data=data.view()
print(view_data)

[91 46 38 92 57 60 37 45 83 57 74 95 77 60 48 39 71 92]


In [25]:
print(copy_data)

[91 46 38 92 57 60 37 45 83 57 74 95 77 60 48 39 71 92]


In [26]:
copy_data[2]=33
print(copy_data)

[91 46 33 92 57 60 37 45 83 57 74 95 77 60 48 39 71 92]


In [27]:
print(copy_data)
print(view_data)
print(data)

[91 46 33 92 57 60 37 45 83 57 74 95 77 60 48 39 71 92]
[91 46 38 92 57 60 37 45 83 57 74 95 77 60 48 39 71 92]
[91 46 38 92 57 60 37 45 83 57 74 95 77 60 48 39 71 92]


In [30]:
view_data[3]=10
print(view_data)

[91 46 38 10 57 60 37 45 83 57 74 95 77 60 48 39 71 92]


In [31]:
print(copy_data)
print(view_data)
print(data)

[91 46 33 92 57 60 37 45 83 57 74 95 77 60 48 39 71 92]
[91 46 38 10 57 60 37 45 83 57 74 95 77 60 48 39 71 92]
[91 46 38 10 57 60 37 45 83 57 74 95 77 60 48 39 71 92]


In [36]:
id(copy_data)

2080033889840

In [35]:
dir(np)

['False_',
 'ScalarType',
 'True_',
 '_CopyMode',
 '_NoValue',
 '__NUMPY_SETUP__',
 '__all__',
 '__array_api_version__',
 '__array_namespace_info__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__dir__',
 '__doc__',
 '__expired_attributes__',
 '__file__',
 '__former_attrs__',
 '__future_scalars__',
 '__getattr__',
 '__loader__',
 '__name__',
 '__numpy_submodules__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_array_api_info',
 '_core',
 '_distributor_init',
 '_expired_attrs_2_0',
 '_globals',
 '_int_extended_msg',
 '_mat',
 '_msg',
 '_pyinstaller_hooks_dir',
 '_pytesttester',
 '_specific_msg',
 '_type_info',
 '_typing',
 '_utils',
 'abs',
 'absolute',
 'acos',
 'acosh',
 'add',
 'all',
 'allclose',
 'amax',
 'amin',
 'angle',
 'any',
 'append',
 'apply_along_axis',
 'apply_over_axes',
 'arange',
 'arccos',
 'arccosh',
 'arcsin',
 'arcsinh',
 'arctan',
 'arctan2',
 'arctanh',
 'argmax',
 'argmin',
 'argpartition',
 'argsort',
 'argwhere',
 'around',
 'array',
 'arr

In [37]:
id(view_data)

2080031866672

In [38]:
id(data)

2080033897328

## Join, Split, Sort, Filter, Search

Manipulating the structure and content of arrays is a **core skill in NumPy**.

---

### 🔹 Joining

Putting the contents of two or more arrays into a single array using:

- `np.concatenate()`
- `np.stack()`

In [58]:
import numpy as np
a=np.array([[1,3,4,5,7,9]])
b=np.array([[7,8,9,5,9,2]])

In [59]:
joined=np.concatenate((a,b))
print(joined)

[[1 3 4 5 7 9]
 [7 8 9 5 9 2]]


In [60]:
joined1=np.stack((a,b))
print(joined1)

[[[1 3 4 5 7 9]]

 [[7 8 9 5 9 2]]]


In [61]:
jooo=np.vstack((a,b))
print(jooo)

[[1 3 4 5 7 9]
 [7 8 9 5 9 2]]


In [62]:
jooo=np.hstack((a,b))
print(jooo)

[[1 3 4 5 7 9 7 8 9 5 9 2]]


### 🔹 Splitting

Breaking one array into multiple arrays using:

- `np.array_split(data, number)` Split 1D or 2D arrays into equal parts

In [ ]:
arr_big = np.array([1, 2, 3, 4, 5, 6])
split
print(spilitted)

In [64]:
# --- SORTING ---

unsorted = np.array([3, 1, 2, 5, 4])
sorted_arr = np.sort(unsorted)[::-1]
print(f"Original: {unsorted}")
print(f"Sorted:   {sorted_arr}")

Original: [3 1 2 5 4]
Sorted:   [5 4 3 2 1]


In [70]:
arr_2d_rand = np.array([[3, 2, 4], [5, 0, 1]])#sorting 2d array
y=np.sort(arr_2d_rand,)
print(y)

[[2 3 4]
 [0 1 5]]


In [71]:
rr_2d_rand = np.array([[3, 2, 4], [5, 0, 1]])#sorting 2d array
y=np.sort(arr_2d_rand)
print(y)

[[2 3 4]
 [0 1 5]]


In [72]:
z=np.sort(y)[:,::-1]
print(z)

[[4 3 2]
 [5 1 0]]


In [86]:
# Searchsorted (Binary Search) - finds where value should be inserted to maintain order
sorted_base = np.array([1, 3, 5, 9])

insert_idx = np.searchsorted(sorted_base, 8)
print(f"Insert 4 into {sorted_base} at index: {insert_idx}")


Insert 4 into [1 3 5 9] at index: 3


In [85]:

sorted_base1 = np.array([1, 3, 5, 7])
sorted_base1[3]=8
print(sorted_base1)

[1 3 5 8]


## 3. Working with Missing Data in NumPy

Unlike **Pandas**, standard **NumPy integer arrays** do not support missing values (`NaN`).  
To work with missing data, the array usually needs to be of type **float** or **object**.

### 🔹 Key Concepts

- **`np.nan`**  
  Represents a missing or undefined value (*Not a Number*).

- **`np.isnan()`**  
  Checks which elements are missing.

- **`np.nansum()`**, **`np.nanmean()`**  
  Perform arithmetic operations while safely ignoring `NaN` values.

In [87]:
# Create an array with missing data (must be float)
data = np.array([1.0, 2.0, np.nan, 4.0, 5.0, np.nan])

print(f"Array with NaNs: {data}")
# Detect missing values
bool_miss = np.isnan(data)
print(f"Is NaN?: {bool_miss}")

# Count missing values
print(f"Count of NaNs: {np.sum(bool_miss)}")


Array with NaNs: [ 1.  2. nan  4.  5. nan]


standard fail: nan


In [90]:
# 3. Standard aggregation fails with NaN
print(f"Standard Sum (fails): {np.sum(data)}")


# 4. Safe aggregation (ignoring NaNs)
print(f"Safe Sum (nansum): {np.nansum(data)}")
print(f"Safe Mean (nanmean): {np.nanmean(data)}")


Standard Sum (fails): nan
Safe Sum (nansum): 12.0
Safe Mean (nanmean): 3.0


In [91]:
# 5. Removing NaNs
clean_data = data[~np.isnan(data)]
print(f"Data with NaNs removed: {clean_data}")

# 6. Filling NaNs with a value (e.g., 0)
filled_data = np.copy(data)
filled_data[np.isnan(filled_data)] = 0
print(f"Data with NaNs filled with 0: {filled_data}")

Data with NaNs removed: [1. 2. 4. 5.]
Data with NaNs filled with 0: [1. 2. 0. 4. 5. 0.]
